from fastapi import FastAPI
from data_access import MySQLDataService
from typing import Optional
import uvicorn

app = FastAPI()

# MySQL connection settings
db_context = {
    "host": "w4153.cl9cloxvh1sk.us-east-1.rds.amazonaws.com",
    "user": "root",
    "password": "dbpassuser",
    "port": 3306
}

data_service = MySQLDataService(db_context)

# Game Model
class Game(BaseModel):
    gameId: Optional[str] = None  # Optional since it will be generated by the database
    image: Optional[bytes] = None  # Using bytes for BLOB
    title: str
    description: str


@app.get("/games")
def fetch_games():
    games_data = data_service.get_all_data_objects(database_name="Game", collection_name="game_info")

    if not games_data:
        return {"message": "No games found"}

    # Convert the fetched data into Game model instances
    games = [
        Game(
            gameId=game["gameId"],
            image=game["image"],
            title=game["title"],
            description=game["description"]
        ) for game in games_data
    ]

    return games

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)